{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "releaseops-service.fullname" . }}-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "releaseops-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressFromNamespaceLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
{{- end }}
