apiVersion: v1
kind: Namespace
metadata:
  name: releaseops
  labels:
    app.kubernetes.io/part-of: releaseops
    platform.releaseops.io/tier: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: releaseops
    platform.releaseops.io/tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: releaseops
    platform.releaseops.io/tier: gitops

