apiVersion: v1
kind: ResourceQuota
metadata:
  name: releaseops-compute-quota
  namespace: releaseops
  labels:
    app.kubernetes.io/part-of: releaseops
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"